name: noctua
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  # Gerenciador de estados
  get: ^4.6.5
  # Google
  google_fonts: ^3.0.1  
  # Back4app
  parse_server_sdk_flutter: ^3.1.3
  # upload Files
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.8
  file_picker: ^5.0.1
  # flutter.dev
  url_launcher: ^6.1.5
  # outros
  validatorless: ^1.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/